// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"tickets/internal/app/http/handler"
	"tickets/internal/app/http/router"
	"tickets/internal/app/pubsub/handler/bookingcanceled"
	"tickets/internal/app/pubsub/handler/bookingconfirmed"
	router2 "tickets/internal/app/pubsub/router"
	"tickets/internal/domain/usecase/show"
	"tickets/internal/domain/usecase/ticket"
	"tickets/internal/domain/usecase/tracker"
	"tickets/internal/provider/db"
	"tickets/internal/provider/eventbus/redisstream"
	"tickets/internal/provider/filestorage/filestorageapi"
	"tickets/internal/provider/gateway"
	"tickets/internal/provider/receipt/receiptsvc"
	"tickets/internal/provider/repo/pg"
	"tickets/internal/provider/spreadsheet/spreadsheetapi"
)

// Injectors from wire.go:

func New() Service {
	dbDB := db.NewDB()
	showRepo := pg.NewShowRepo(dbDB)
	create := show.NewCreate(showRepo)
	showHandler := handler.NewShowHandler(create)
	eventBus := redisstream.NewEventBus()
	postStatus := ticket.NewPostStatus(eventBus)
	ticketRepo := pg.NewTicketRepo(dbDB)
	list := ticket.NewList(ticketRepo)
	ticketHandler := handler.NewTicketHandler(postStatus, list)
	healthHandler := handler.NewHealthHandler()
	echo := router.New(showHandler, ticketHandler, healthHandler)
	clients := gateway.NewGateway()
	client := spreadsheetapi.NewClient(clients)
	appendCanceledBooking := tracker.NewAppendCanceledBooking(client)
	appendToTracker := bookingcanceled.NewAppendToTracker(appendCanceledBooking)
	appendConfirmedBooking := tracker.NewAppendConfirmedBooking(client)
	bookingconfirmedAppendToTracker := bookingconfirmed.NewAppendToTracker(appendConfirmedBooking)
	receiptsvcClient := receiptsvc.NewClient(clients)
	issueReceipt := ticket.NewIssueReceipt(receiptsvcClient)
	bookingconfirmedIssueReceipt := bookingconfirmed.NewIssueReceipt(issueReceipt)
	ticketCreate := ticket.NewCreate(ticketRepo)
	createTicket := bookingconfirmed.NewCreateTicket(ticketCreate)
	ticketDelete := ticket.NewDelete(ticketRepo)
	deleteTicket := bookingcanceled.NewDeleteTicket(ticketDelete)
	filestorageapiClient := filestorageapi.NewClient(clients)
	ticketPrint := ticket.NewPrint(filestorageapiClient, eventBus)
	printTicket := bookingconfirmed.NewPrintTicket(ticketPrint)
	routerRouter := router2.NewRouter(eventBus, appendToTracker, bookingconfirmedAppendToTracker, bookingconfirmedIssueReceipt, createTicket, deleteTicket, printTicket)
	service := Service{
		db:           dbDB,
		httpRouter:   echo,
		pubSubRouter: routerRouter,
	}
	return service
}
